spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/musiq_db
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true